# Generated by Django 5.1.7 on 2025-08-19 23:48

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model("market", "Category")

    # Define categories and subcategories
    categories = {
        "": [],
        "Books": ["Textbooks", "Novels", "Comics", "Magazines", "Past Questions", "E-Books", "PDF's", "Research Papers"],
        "Gadgets": ["Phones", "Laptops", "Accessories", "Power Banks", "Chargers", "Smartwatches"],
        "Notes": ["Lecture Notes", "Past Questions"],
        "Stationery": ["Pens", "Notebooks", "Calculators", "Drawing Boards", "Painting Materials"],
        "Home Appliances": ["Refrigerators", "Washing Machines", "Microwaves"],
        "Electronics": ["Televisions", "Cameras", "Speakers"],
        "Furniture": ["Chairs", "Tables", "Beds"],
        "Toys": ["Action Figures", "Dolls", "Puzzles"],
        "Tools": ["Drawing Boards", "Hammers", "Screwdrivers", "Wrenches", "Helmets", "Boots"],
        "Housing and Rentals": ["Apartments", "Houses", "Condos", "Hostels", "Shops"],
        "Vehicles": ["Cars", "Bikes", "Trucks", "Buses"],
        "Others": []
    }

    for cat_name, subs in categories.items():
        category, _ = Category.objects.get_or_create(
            name=cat_name,
            slug=cat_name.lower().replace(" ", "-"),
            parent=None,
        )
        for sub in subs:
            Category.objects.get_or_create(
                slug=sub.lower().replace(" ", "-"),
                defaults={"name": sub, "parent": category},
            )

class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
    ]
