# Generated by Django 5.2.5 on 2025-08-24 16:53

from django.db import migrations
from django.utils.text import slugify

def load_categories(apps, schema_editor):
    Category = apps.get_model('market', 'Category')
    
    # First, clear any existing categories to avoid duplicates
    Category.objects.all().delete()
    print("Cleared existing categories")
    
    # Define your categories and subcategories
    categories_data = [
        {
            'name': 'Gadgets',
            'subcategories': ['Phones', 'Laptops', 'Headphones', 'Cameras']
        },
        {
            'name': "Electronics",
            'subcategories': ["Televisions", "Speakers"]
        },
        {
            'name': 'Books', 
            'subcategories': ['Textbooks', 'Fiction', 'Non-Fiction', 'Academic', "Lecture Notes", "Past Questions", "E-Books", "PDF's", "Research Papers"]
        },
        {
            'name': "Home Appliances",
            'subcategories': ["Refrigerators", "Washing Machines", "Microwaves"]
        },
        {
            'name': "Housing and Rentals",
            'subcategories': ["Apartments", "Houses", "Condos", "Hostels", "Shops"]
        },
        {
            'name': "Vehicles",
            'subcategories': ["Cars", "Bikes", "Trucks", "Buses"]
        },
        {
            'name': "Tools",
            'subcategories': ["Hammers", "Screwdrivers", "Wrenches", "Helmets", "Boots"]
        },
        {
            'name': 'Clothing',
            'subcategories': ['Men', 'Women', 'Accessories', 'Shoes', 'Watch']
        },
        {
            'name': 'Furniture',
            'subcategories': ['Chairs', 'Tables', 'Beds', 'Storage']
        },
        {
            'name': 'Services',
            'subcategories': ['Tutoring', 'Coding', 'Repair', 'Delivery', 'Other Services']
        },
        {
            'name': 'Miscellaneous',
            'subcategories': ['Art Supplies', 'Crafts']
        },
        {
            'name': "Stationery",
            'subcategories': ["Pens", "Notebooks", "Calculators", "Drawing Boards", "Painting Materials"]
        }
    ]
    
    for category_data in categories_data:
        # Create main category
        main_category = Category.objects.create(
            name=category_data['name'],
            slug=slugify(category_data['name'])
        )
        print(f"Created main category: {main_category.name}")
        
        # Create subcategories
        for subcat_name in category_data['subcategories']:
            subcategory = Category.objects.create(
                name=subcat_name,
                parent=main_category,
                slug=f"{main_category.slug}-{slugify(subcat_name)}"
            )
            print(f"  → Created subcategory: {subcategory.name}")

def reverse_categories(apps, schema_editor):
    Category = apps.get_model('market', 'Category')
    Category.objects.all().delete()
    print("Reversed: Deleted all categories")

class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(load_categories, reverse_categories),
    ]
