# Generated by Django 5.2.5 on 2025-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('secondary', 'Secondary'), ('undergraduate', 'Undergraduate'), ('tertiary', 'Tertiary Instituition'), ('postgraduate', 'Postgraduate')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
