# Generated by Django 5.1.7 on 2025-04-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='educationlevel',
            field=models.CharField(choices=[('secondary', 'Secondary'), ('undergraduate', 'Undergraduate'), ('tertiary', 'Tertiary Instituition'), ('postgraduate', 'Postgraduate')], default='secondary', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default='', max_length=250),
        ),
    ]
