# Generated by Django 5.1.7 on 2025-04-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_educationlevel_profile_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='educationlevel',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
    ]
