# Generated by Django 5.2.5 on 2025-08-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('alert', 'Alert'), ('invite', 'Invite'), ('request', 'Request'), ('reminder', 'Reminder'), ('update', 'Update'), ('warning', 'Warning'), ('info', 'Info'), ('error', 'Error'), ('success', 'Success'), ('message', 'Message'), ('like', 'Like'), ('comment', 'Comment')], default='alert', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.group')),
            ],
        ),
    ]
