# Generated by Django 5.1.7 on 2025-05-16 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_groups_group'),
        ('notifications', '0002_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Alert'), ('invite', 'Invite'), ('Request', 'request'), ('reminder', 'Reminder'), ('update', 'Update'), ('warning', 'Warning'), ('info', 'Info'), ('error', 'Error'), ('success', 'Success'), ('message', 'Message')], default='alert', max_length=20),
        ),
    ]
