# Generated by Django 5.1.7 on 2025-05-16 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_groups_group'),
        ('notifications', '0003_notification_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Alert'), ('invite', 'Invite'), ('request', 'Request'), ('reminder', 'Reminder'), ('update', 'Update'), ('warning', 'Warning'), ('info', 'Info'), ('error', 'Error'), ('success', 'Success'), ('message', 'Message'), ('like', 'Like')], default='alert', max_length=20),
        ),
    ]
