# Generated by Django 5.1.7 on 2025-05-16 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_groups_group'),
        ('notifications', '0004_alter_notification_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.group'),
        ),
    ]
