# Generated by Django 5.1.7 on 2025-04-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_pdfresource_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfresource',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
