# Generated by Django 5.1.7 on 2025-04-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_pdfresource_author_pdfresource_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfresource',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
