# Generated by Django 5.1.7 on 2025-08-17 02:31

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_pdfresource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfresource',
            name='file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pdfs/'),
        ),
    ]
