# Generated by Django 5.1.7 on 2025-05-18 05:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_answeroption_question_memberanswer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberanswer',
            unique_together={('user', 'question')},
        ),
    ]
