# Generated by Django 5.1.7 on 2025-05-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_memberanswer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberanswer', to='groups.question'),
        ),
    ]
